const TOGGLE_SIGNUP = "TOGGLE_SIGNUP";
const TOGGLE_SIGNIN = "TOGGLE_SIGNIN";
const TOGGLE_PASSWORD = "TOGGLE_PASSWORD";
const SHOW_ALERT = "SHOW_ALERT";
const STORE_USER = "STORE_USER";
const REMOVE_USER = "REMOVE_USER";

export {
	TOGGLE_SIGNUP,
	TOGGLE_SIGNIN,
	TOGGLE_PASSWORD,
	SHOW_ALERT,
	STORE_USER,
	REMOVE_USER,
};
